//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        public int QuestionID { get; set; }
        [Display(Name = "Question")]
        [Required(ErrorMessage ="*")]
        public string QuestionText { get; set; }
        [Display(Name = "Option 1")]
        [Required(ErrorMessage = "*")]
        public string OptionA { get; set; }
        [Display(Name = "Option 2")]
        [Required(ErrorMessage = "*")]
        public string OptionB { get; set; }
        [Display(Name = "Option 3")]
        [Required(ErrorMessage = "*")]
        public string OptionC { get; set; }
        [Display(Name = "Option 4")]
        [Required(ErrorMessage = "*")]
        public string OptionD { get; set; }
        [Display(Name = "Correct Answer")]
        [Required(ErrorMessage = "*")]
        public string CorrectOption { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual Category Category1 { get; set; }
    }
}
